"""
This file represents a `eigenvectors.h5` file generated by spinor `absorption`.
"""
struct BerkeleyGWSpinorExciton <: AbstractBSEWaveFunction
    fid :: HDF5.File
    wfn :: BerkeleyGWSpinorWFN
end

function BerkeleyGWSpinorExciton(exciton_hdf::HDF5.File, wfn_hdf::HDF5)
    wfn_header = BerkeleyGWSpinorWFN(wfn_hdf) 
    
    BerkeleyGWSpinorExciton(exciton_hdf, wfn_header)
end

function dipole(wfn::BerkeleyGWSpinorWFN)
    
end